<a href="https://colab.research.google.com/github/aghidottiavbo/ML-CoLab/blob/main/01-IstruzioniBase.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Istruzioni di base

In [3]:
import numpy as np

In [4]:
v1 = np.array([1,2,3])
print(v1)

[1 2 3]


In [5]:
v2 = np.array([[1.3, 2.5, 3.7, 4.8],[2.3, 3.5, 4.7, 5.8]])
print(v2)

[[1.3 2.5 3.7 4.8]
 [2.3 3.5 4.7 5.8]]


In [6]:
v3 = np.array([5, 6, 7], dtype=np.uint8)
print(v3)

[5 6 7]


In [7]:
print(v1.ndim)
print(v1.shape)

1
(3,)


In [8]:
print(v2.ndim)
print(v2.shape)

2
(2, 4)


In [9]:
print(v1.dtype)
print(v1.itemsize)
print(v1.nbytes)

int64
8
24


In [10]:
print(v2.dtype)
print(v2.itemsize)
print(v2.nbytes)

float64
8
64


In [11]:
print(v3.dtype)
print(v3.itemsize)
print(v3.nbytes)

uint8
1
3


# Accesso agli elementi

In [13]:
# Accesso al singolo elemento
print(v2)
print(v2.shape)
print(v2[1,2])

[[1.3 2.5 3.7 4.8]
 [2.3 3.5 4.7 5.8]]
(2, 4)
4.7


In [14]:
# Accesso ad una specifica riga
print( v2[1,:] )

# Accesso ad una specifica riga
print( v2[:,1] )

# Accesso ad un insieme di colonne
print( v2[:,1:2] )

[2.3 3.5 4.7 5.8]
[2.5 3.5]
[[2.5]
 [3.5]]


In [19]:
# Accesso sparso
v4 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(v4[1:-1:2])


v5 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
print(v5[:, 1:-1:2])

[1 3 5 7]
[[1 3 5 7]
 [1 3 5 7]]


In [20]:
# Trasposizione
print(v4.transpose())

[0 1 2 3 4 5 6 7 8 9]
